### ISSUE TITLE
Add projects

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc-ecosystem-ci#6]
```[tasklist]
### Tasks
- [ ] Microsoft
- [ ] stotybook
```

**Comment by kdy1** [comment]
https://github.com/eleme/morjs 989
https://github.com/bkrem/react-d3-tree 957
https://github.com/mattphillips/deep-object-diff 957
https://github.com/testing-library/eslint-plugin-testing-library 918
https://github.com/adonisjs/lucid 902
https://github.com/tinylibs/tinypool 885
https://github.com/VKCOM/VKUI 876
https://github.com/APIDevTools/json-schema-ref-parser 861
https://github.com/next-boost/next-boost 856
https://github.com/ant-design/ant-design-icons 854
https://github.com/thirdweb-dev/contracts 852
https://github.com/axe-me/vite-plugin-node 834
https://github.com/Shopify/shopify-api-js 832
https://github.com/guybedford/es-module-lexer 826
https://github.com/typescript-eslint/tslint-to-eslint-config 818
https://github.com/MichalLytek/typegraphql-prisma 814
https://github.com/tldraw/signia 810
https://github.com/Xetera/ghost-cursor 793
https://github.com/kufu/smarthr-ui 781
https://github.com/alienzhou/web-highlighter 765
https://github.com/storefront-foundation/react-storefront 755
https://github.com/nullstack/nullstack 753
https://github.com/JuneAndGreen/sm-crypto 743
https://github.com/swc-project/jest 739
https://github.com/discordeno/discordeno 731
https://github.com/Stanko/react-animate-height 713
https://github.com/rolldown-rs/rolldown_legacy 709
https://github.com/blocknative/web3-onboard 696
https://github.com/midwayjs/hooks 690
https://github.com/module-federation/universe 688
https://github.com/FlamingTempura/bibtex-tidy 662
https://github.com/getsentry/sentry-webpack-plugin 660
https://github.com/EtherealEngine/etherealengine 647
https://github.com/SukkaW/nolyfill 644
https://github.com/florianholzapfel/express-restify-mongoose 638
https://github.com/tailwindlabs/tailwindcss-container-queries 637
https://github.com/mikecousins/react-pdf-js 631
https://github.com/umijs/umi-next 617
https://github.com/99x/serverless-dynamodb-local 616
https://github.com/MetaMask/snaps 615
https://github.com/SukkaW/DisqusJS 615
https://github.com/ts-plugin/ts-import-plugin 611
https://github.com/wechat-miniprogram/computed 610
https://github.com/jpmorganchase/modular 602
https://github.com/vinejs/vine 601
https://github.com/kriskowal/asap 601
https://github.com/CromwellCMS/Cromwell 585
https://github.com/gemini-testing/hermione 585
https://github.com/fab-spec/fab 578
https://github.com/vitejs/vite-plugin-react-swc 574
https://github.com/mui/mui-toolpad 570
https://github.com/nachoaldamav/ultra 561
https://github.com/GuillaumeLeclerc/vue-google-maps 557
https://github.com/coatue-oss/react2angular 547
https://github.com/zenn-dev/zenn-editor 524
https://github.com/smashtestio/smashtest 513
https://github.com/ds300/lazyrepo 505
https://github.com/divriots/jampack 503
https://github.com/aelbore/esbuild-jest 503
https://github.com/magicdawn/yun-playlist-downloader 497
https://github.com/edge-js/edge 492
https://github.com/xaviergonz/mobx-keystone 481
https://github.com/wessberg/rollup-plugin-ts 472
https://github.com/objectiv/objectiv-analytics 464
https://github.com/antfu/starter-ts 463
https://github.com/notiz-dev/nestjs-prisma 463
https://github.com/huozhi/bunchee 462
https://github.com/cnpm/cnpmcore 461
https://github.com/unlight/prisma-nestjs-graphql 459
https://github.com/causaly/zod-validation-error 458
https://github.com/bs-community/skinview3d 449
https://github.com/sannajammeh/tw-classed 445
https://github.com/scaffold-eth/eth-ui 437
https://github.com/temporalio/sdk-typescript 433
https://github.com/RobinTail/express-zod-api 430
https://github.com/chintan9/plyr-react 429
https://github.com/nxext/nx-extensions 418
https://github.com/romeerez/orchid-orm 416
https://github.com/talyssonoc/react-katex 409
https://github.com/dohomi/react-hook-form-mui 406
https://github.com/listr2/listr2 400
https://github.com/Uniswap/v2-sdk 398
https://github.com/sonofmagic/weapp-tailwindcss 398
https://github.com/Sh4yy/vercel-email 398
https://github.com/use-cookie-consent/use-cookie-consent 396
https://github.com/swc-project/swc-loader 395
https://github.com/japa/runner 388
https://github.com/japa/core 371
https://github.com/fractures/fractures 366
https://github.com/placemark/togeojson 364
https://github.com/RobinMalfait/lazy-collections 351
https://github.com/scolladon/sfdx-git-delta 337
https://github.com/hcg1023/vue3-dnd 333
https://github.com/vercel/analytics 332
https://github.com/unstubbable/mfng 332
https://github.com/bitloops/bitloops-language 331
https://github.com/adonisjs/ace 327
https://github.com/fabien0102/openapi-codegen 325
https://github.com/egoist/esmon 324
https://github.com/ntegral/nestjs-sentry 324
https://github.com/functionless/functionless 323
https://github.com/DuCanhGH/next-pwa 317
https://github.com/TexteaInc/json-viewer 315
https://github.com/egoist/ts-lib-starter 297
https://github.com/nytimes/react-prosemirror 297
https://github.com/gilbarbara/react-spotify-web-playback 289
https://github.com/roots/bud 288
https://github.com/dawsbot/essential-eth 287
https://github.com/sodium-friends/sodium-native 287
https://github.com/Niels-IO/next-image-export-optimizer 287
https://github.com/fastify/fastify-autoload 284
https://github.com/adrien2p/medusa-extender 284
https://github.com/NaturalSelectionLabs/Unidata 283
https://github.com/dc7290/next-export-optimize-images 282
https://github.com/ossjs/release 282
https://github.com/taoyage/yg-configs 278
https://github.com/awslabs/amazon-neptune-tools 277
https://github.com/htunnicliff/next-api-middleware 270
https://github.com/napi-rs/package-template 260
https://github.com/yarnaimo/fireschema 259
https://github.com/AndrejJurkin/create-tw 254
https://github.com/thirdweb-dev/js 247
https://github.com/jmcdo29/nestjs-spelunker 247
https://github.com/foca-js/foca 247
https://github.com/sanack/node-jq 243
https://github.com/graphcommerce-org/graphcommerce 240
https://github.com/shmuelhizmi/web-desktop-environment 238
https://github.com/sachinraja/zod-to-ts 229
https://github.com/h3poteto/megalodon 228
https://github.com/valentinpalkovic/prisma-json-schema-generator 222
https://github.com/coinbase/cbpay-js 220
https://github.com/jlalmes/trpc-chrome 219
https://github.com/47ng/chakra-next 217
https://github.com/anuoua/unis 216
https://github.com/Tinkoff/tramvai 215
https://github.com/stephenh/joist-ts 212
https://github.com/asyncapi/modelina 210
https://github.com/github/codespaces-blank 206
https://github.com/ryansonshine/typescript-npm-package-template 204
https://github.com/SauravKanchan/svelte-chartjs 204
https://github.com/wechaty/puppet 203
https://github.com/magicdawn/weread-spy 203
https://github.com/unplugin/unplugin-swc 203
https://github.com/ThePrimeagen/undefined 200
https://github.com/jonataswalker/ol-contextmenu 198
https://github.com/payloadcms/next-payload 197
https://github.com/sonnyt/just 197
https://github.com/theKashey/devolution 195
https://github.com/DTStack/dt-sql-parser 195
https://github.com/vaheqelyan/react-awesome-popover 194
https://github.com/datalanche/node-pg-format 193
https://github.com/samhh/fp-ts-std 192
https://github.com/jerrywu001/vue3-toastify 191
https://github.com/nxtend-team/nxtend 191
https://github.com/sphinx-labs/sphinx 186
https://github.com/JasKang/rubic 186
https://github.com/eggjs/egg-bin 185
https://github.com/romgrk/web-toolkit 184
https://github.com/jasonraimondi/ts-oauth2-server 184
https://github.com/gilbarbara/react-floater 183
https://github.com/Zapper-fi/studio 183
https://github.com/muxinc/elements 179
https://github.com/bjorn3/browser_wasi_shim 178
https://github.com/jaebradley/example-rollup-react-component-npm-package 178
https://github.com/ice-lab/icepkg 178
https://github.com/osmosis-labs/osmosis-frontend 175
https://github.com/Gabb-c/pokenode-ts 173
https://github.com/Himenon/openapi-typescript-code-generator 171
https://github.com/milesj/packemon 169
https://github.com/shaoruu/voxelize 167
https://github.com/Atyantik/pawjs 165
https://github.com/wechat-miniprogram/mobx-miniprogram-bindings 165
https://github.com/codermarcos/simple-mask-money 164
https://github.com/shuding/yoga-wasm-web 160
https://github.com/DevYukine/Kurasuta 160
https://github.com/skyllo/peer-lite 159
https://github.com/cgxqd/utilscore 158
https://github.com/storybookjs/test-runner 158
https://github.com/kubb-project/kubb 157
https://github.com/diegoazh/gmap-vue 156
https://github.com/leon-ai/leon-cli 156
https://github.com/agiliumtrade-ai/metaapi-node.js-sdk 156
https://github.com/SUI-Components/sui 155
https://github.com/Menci/vite-plugin-top-level-await 154
https://github.com/demergent-labs/azle 153
https://github.com/pixelass/react-stickyroll 152
https://github.com/ShogunPanda/fastimage 152
https://github.com/storybookjs/telejson 151
https://github.com/BySlin/umi-plugin-electron-builder 150
https://github.com/natalan/samsung-remote 150
https://github.com/getjerry/nest-casl 149
https://github.com/nextjs-components/nextjs-components 149
https://github.com/chialab/rna 149
https://github.com/jspm/generator 148
https://github.com/sladg/nextjs-lambda 148
https://github.com/tada5hi/typeorm-extension 144
https://github.com/pveyes/raw.macro 144
https://github.com/yamadapc/augmented-audio 143
https://github.com/yowainwright/shave 143
https://github.com/asyncapi/cli 142
https://github.com/dano-inc/react-query-helper 142
https://github.com/himself65/rich-data 141
https://github.com/adonisjs/ally 141
https://github.com/Janpot/next-rpc 139
https://github.com/Jack-Works/async-call-rpc 138
https://github.com/channel-io/bezier-react 138
https://github.com/jinxdash/prettier-plugin-rust 137
https://github.com/ArunMichaelDsouza/joypad.js 137
https://github.com/pmndrs/react-ogl 137
https://github.com/thirdweb-dev/typescript-sdk 136
https://github.com/microcmsio/microcms-js-sdk 134
https://github.com/wintercounter/mhy 134
https://github.com/mantoufan/yzhanWeather 133
https://github.com/infinum/datx 133
https://github.com/pubnub/react-chat-components 132
https://github.com/Brooooooklyn/pinyin 130
https://github.com/alfredosalzillo/rollup-plugin-multi-input 128
https://github.com/pradel/create-react-app-swc 128
https://github.com/SukkaW/rollup-plugin-swc 125
https://github.com/favware/graphql-pokemon 125
https://github.com/wessberg/Polyfiller 123
https://github.com/basilfx/normalize-wheel 123
https://github.com/maugenst/tabletojson 123
https://github.com/nrwl/nx-labs 122
https://github.com/SaltyAom/kingworld 120
https://github.com/swc-project/cli 120
https://github.com/storybookjs/addon-kit 117
https://github.com/zackradisic/tyfsm 117
https://github.com/CodelyTV/typescript-basic-skeleton 117
https://github.com/mizdra/happy-css-modules 115
https://github.com/n8n-io/n8n-nodes-starter 114
https://github.com/javascriptdata/scikit.js 113
https://github.com/OMikkel/tailwind-datepicker-react 111
https://github.com/texei/texei-sfdx-plugin 110
https://github.com/ssssota/svg2png-wasm 109
https://github.com/adonisjs/validator 108
https://github.com/shannonhochkins/ha-component-kit 108
https://github.com/prettydiff/share-file-systems 108
https://github.com/mantoufan/yzhanHTMLParser 108
https://github.com/gadget-inc/wds 108
https://github.com/adonisjs/fold 107
https://github.com/nwpointer/three-landscape 105
https://github.com/VKCOM/icons 104
https://github.com/upgradejs/depngn 103
https://github.com/goldstack/goldstack 103
https://github.com/asyncapi/parser-js 101
https://github.com/jungomi/xxhash-wasm 101
https://github.com/SocialGouv/code-du-travail-numerique 101
https://github.com/faasjs/faasjs 101
https://github.com/jasonkuhrt/alge 101
https://github.com/CodelyTV/typescript-primitives-type 100

**Comment by kdy1** [comment]
- [x] https://github.com/UnblockNeteaseMusic/server 4500
- [ ] https://github.com/smogon/pokemon-showdown 4300
- [ ] https://github.com/Atri-Labs/atrilabs-engine 4200
- [ ] https://github.com/webpro/knip 3700
- [ ] https://github.com/dvtng/react-loading-skeleton 3600
- [ ] https://github.com/canvg/canvg 3500
- [ ] https://github.com/sofn-xyz/mailing 3500
- [ ] https://github.com/rollup/plugins 3400
- [ ] https://github.com/shadowwalker/next-pwa 3300
- [ ] https://github.com/umijs/dumi 3200
- [ ] https://github.com/stevenpetryk/mafs 3100
- [ ] https://github.com/outline/rich-markdown-editor 2800
- [ ] https://github.com/vvo/iron-session 2800
- [ ] https://github.com/arktypeio/arktype 2700
- [ ] https://github.com/creativetimofficial/material-tailwind 2600
- [ ] https://github.com/bcherny/json-schema-to-typescript 2600
- [ ] https://github.com/pancakeswap/pancake-frontend 2400
- [ ] https://github.com/zhangyuang/ssr 2400
- [ ] https://github.com/lowdefy/lowdefy 2400
- [ ] https://github.com/mlaursen/react-md 2400
- [ ] https://github.com/LegendApp/legend-state 2200
- [ ] https://github.com/motifland/markprompt 2200
- [ ] https://github.com/nvh95/jest-preview 2200
- [ ] https://github.com/efoxTeam/emp 2200
- [ ] https://github.com/theoephraim/node-google-spreadsheet 2100
- [ ] https://github.com/dollarshaveclub/shave 2100
- [ ] https://github.com/hayes/pothos 2100
- [ ] https://github.com/apache/incubator-opendal 2000
- [ ] https://github.com/xkjyeah/vue-google-maps 1900
- [ ] https://github.com/webpack-contrib/terser-webpack-plugin 1900
- [ ] https://github.com/umijs/father 1900
- [ ] https://github.com/Ironclad/rivet 1800
- [x] https://github.com/nestjs/nest-cli 1800
- [ ] https://github.com/anymaniax/orval 1700
- [ ] https://github.com/babel/babelify 1700
- [ ] https://github.com/react-hookz/web 1600
- [ ] https://github.com/dai-shi/waku 1600
- [ ] https://github.com/junhoyeo/threads-api 1600
- [ ] https://github.com/master-co/css 1600
- [ ] https://github.com/alex8088/electron-vite 1600
- [ ] https://github.com/solana-labs/solana-web3.js 1500
- [x] https://github.com/swc-project/swc-node 1500
- [ ] https://github.com/rakannimer/react-google-charts 1500
- [ ] https://github.com/ts-rest/ts-rest 1500
- [ ] https://github.com/prisma/prisma-client-js 1500
- [ ] https://github.com/Brooooooklyn/canvas 1400
- [ ] https://github.com/nextui-org/tailwind-variants 1400
- [ ] https://github.com/belgattitude/nextjs-monorepo-example 1300
- [ ] https://github.com/electron-vite/electron-vite-react 1300
- [ ] https://github.com/KidkArolis/jetpack 1300
- [ ] https://github.com/smartxworks/sunmao-ui 1300
- [ ] https://github.com/microsoft/rnx-kit 1300
- [ ] https://github.com/vega/ts-json-schema-generator 1200
- [ ] https://github.com/gilbarbara/react-inlinesvg 1200
- [ ] https://github.com/WeBankFinTech/fes.js 1200
- [ ] https://github.com/omnidan/node-emoji 1200
- [ ] https://github.com/mapbox/togeojson 1200
- [ ] https://github.com/vercel/react-tweet 1100
- [ ] https://github.com/yisibl/resvg-js 1100
- [ ] https://github.com/alibaba/dawn 1100
- [ ] https://github.com/mdn/yari 1100
- [ ] https://github.com/dgreif/ring 1000
- [ ] https://github.com/Urigo/SOFA 1000
- [ ] https://github.com/eleme/morjs 989
- [ ] https://github.com/bkrem/react-d3-tree 957
- [ ] https://github.com/mattphillips/deep-object-diff 957
- [ ] https://github.com/testing-library/eslint-plugin-testing-library 918
- [ ] https://github.com/adonisjs/lucid 902
- [ ] https://github.com/tinylibs/tinypool 885
- [ ] https://github.com/VKCOM/VKUI 876
- [ ] https://github.com/APIDevTools/json-schema-ref-parser 861
- [ ] https://github.com/next-boost/next-boost 856
- [ ] https://github.com/ant-design/ant-design-icons 854
- [ ] https://github.com/thirdweb-dev/contracts 852
- [ ] https://github.com/axe-me/vite-plugin-node 834
- [ ] https://github.com/Shopify/shopify-api-js 832
- [ ] https://github.com/guybedford/es-module-lexer 826
- [ ] https://github.com/typescript-eslint/tslint-to-eslint-config 818
- [ ] https://github.com/MichalLytek/typegraphql-prisma 814
- [ ] https://github.com/tldraw/signia 810
- [ ] https://github.com/Xetera/ghost-cursor 793
- [ ] https://github.com/kufu/smarthr-ui 781
- [ ] https://github.com/alienzhou/web-highlighter 765
- [ ] https://github.com/storefront-foundation/react-storefront 755
- [ ] https://github.com/nullstack/nullstack 753
- [ ] https://github.com/JuneAndGreen/sm-crypto 743
- [x] https://github.com/swc-project/jest 739
- [ ] https://github.com/discordeno/discordeno 731
- [ ] https://github.com/Stanko/react-animate-height 713
- [ ] https://github.com/rolldown-rs/rolldown_legacy 709
- [ ] https://github.com/blocknative/web3-onboard 696
- [ ] https://github.com/midwayjs/hooks 690
- [ ] https://github.com/module-federation/universe 688
- [ ] https://github.com/FlamingTempura/bibtex-tidy 662
- [ ] https://github.com/getsentry/sentry-webpack-plugin 660
- [ ] https://github.com/EtherealEngine/etherealengine 647
- [ ] https://github.com/SukkaW/nolyfill 644
- [ ] https://github.com/florianholzapfel/express-restify-mongoose 638
- [ ] https://github.com/tailwindlabs/tailwindcss-container-queries 637
- [ ] https://github.com/mikecousins/react-pdf-js 631
- [ ] https://github.com/umijs/umi-next 617
- [ ] https://github.com/99x/serverless-dynamodb-local 616
- [ ] https://github.com/SukkaW/DisqusJS 615
- [ ] https://github.com/MetaMask/snaps 615
- [ ] https://github.com/ts-plugin/ts-import-plugin 611
- [ ] https://github.com/wechat-miniprogram/computed 610
- [ ] https://github.com/jpmorganchase/modular 602
- [ ] https://github.com/vinejs/vine 601
- [ ] https://github.com/kriskowal/asap 601
- [ ] https://github.com/CromwellCMS/Cromwell 585
- [ ] https://github.com/gemini-testing/hermione 585
- [ ] https://github.com/fab-spec/fab 578
- [ ] https://github.com/vitejs/vite-plugin-react-swc 574
- [ ] https://github.com/mui/mui-toolpad 570
- [ ] https://github.com/nachoaldamav/ultra 561
- [ ] https://github.com/GuillaumeLeclerc/vue-google-maps 557
- [ ] https://github.com/coatue-oss/react2angular 547
- [ ] https://github.com/zenn-dev/zenn-editor 524
- [ ] https://github.com/smashtestio/smashtest 513
- [ ] https://github.com/ds300/lazyrepo 505
- [ ] https://github.com/aelbore/esbuild-jest 503
- [ ] https://github.com/divriots/jampack 503
- [ ] https://github.com/magicdawn/yun-playlist-downloader 497
- [ ] https://github.com/edge-js/edge 492
- [ ] https://github.com/xaviergonz/mobx-keystone 481
- [ ] https://github.com/wessberg/rollup-plugin-ts 472
- [ ] https://github.com/objectiv/objectiv-analytics 464
- [ ] https://github.com/notiz-dev/nestjs-prisma 463
- [ ] https://github.com/antfu/starter-ts 463
- [x] https://github.com/huozhi/bunchee 462
- [ ] https://github.com/cnpm/cnpmcore 461
- [ ] https://github.com/unlight/prisma-nestjs-graphql 459
- [ ] https://github.com/causaly/zod-validation-error 458
- [ ] https://github.com/bs-community/skinview3d 449
- [ ] https://github.com/sannajammeh/tw-classed 445
- [ ] https://github.com/scaffold-eth/eth-ui 437
- [ ] https://github.com/temporalio/sdk-typescript 433
- [ ] https://github.com/RobinTail/express-zod-api 430
- [ ] https://github.com/chintan9/plyr-react 429
- [ ] https://github.com/nxext/nx-extensions 418
- [ ] https://github.com/romeerez/orchid-orm 416
- [ ] https://github.com/talyssonoc/react-katex 409
- [ ] https://github.com/dohomi/react-hook-form-mui 406
- [ ] https://github.com/listr2/listr2 400
- [ ] https://github.com/sonofmagic/weapp-tailwindcss 398
- [ ] https://github.com/Uniswap/v2-sdk 398
- [ ] https://github.com/Sh4yy/vercel-email 398
- [ ] https://github.com/use-cookie-consent/use-cookie-consent 396
- [ ] https://github.com/swc-project/swc-loader 395
- [ ] https://github.com/japa/runner 388
- [ ] https://github.com/japa/core 371
- [ ] https://github.com/fractures/fractures 366
- [ ] https://github.com/placemark/togeojson 364
- [ ] https://github.com/RobinMalfait/lazy-collections 351
- [ ] https://github.com/scolladon/sfdx-git-delta 337
- [ ] https://github.com/hcg1023/vue3-dnd 333
- [ ] https://github.com/unstubbable/mfng 332
- [x] https://github.com/vercel/analytics 332
- [ ] https://github.com/bitloops/bitloops-language 331
- [ ] https://github.com/adonisjs/ace 327
- [ ] https://github.com/fabien0102/openapi-codegen 325
- [ ] https://github.com/egoist/esmon 324
- [ ] https://github.com/ntegral/nestjs-sentry 324
- [ ] https://github.com/functionless/functionless 323
- [ ] https://github.com/DuCanhGH/next-pwa 317
- [ ] https://github.com/TexteaInc/json-viewer 315
- [ ] https://github.com/egoist/ts-lib-starter 297
- [ ] https://github.com/nytimes/react-prosemirror 297
- [ ] https://github.com/gilbarbara/react-spotify-web-playback 289
- [ ] https://github.com/roots/bud 288
- [ ] https://github.com/dawsbot/essential-eth 287
- [ ] https://github.com/Niels-IO/next-image-export-optimizer 287
- [ ] https://github.com/sodium-friends/sodium-native 287
- [ ] https://github.com/adrien2p/medusa-extender 284
- [ ] https://github.com/fastify/fastify-autoload 284
- [ ] https://github.com/NaturalSelectionLabs/Unidata 283
- [ ] https://github.com/ossjs/release 282
- [ ] https://github.com/dc7290/next-export-optimize-images 282
- [ ] https://github.com/taoyage/yg-configs 278
- [ ] https://github.com/awslabs/amazon-neptune-tools 277
- [ ] https://github.com/htunnicliff/next-api-middleware 270
- [ ] https://github.com/napi-rs/package-template 260
- [ ] https://github.com/yarnaimo/fireschema 259
- [ ] https://github.com/AndrejJurkin/create-tw 254
- [ ] https://github.com/jmcdo29/nestjs-spelunker 247
- [ ] https://github.com/foca-js/foca 247
- [ ] https://github.com/thirdweb-dev/js 247
- [ ] https://github.com/sanack/node-jq 243
- [ ] https://github.com/graphcommerce-org/graphcommerce 240
- [ ] https://github.com/shmuelhizmi/web-desktop-environment 238
- [ ] https://github.com/sachinraja/zod-to-ts 229
- [ ] https://github.com/h3poteto/megalodon 228
- [ ] https://github.com/valentinpalkovic/prisma-json-schema-generator 222
- [ ] https://github.com/coinbase/cbpay-js 220
- [ ] https://github.com/jlalmes/trpc-chrome 219
- [ ] https://github.com/47ng/chakra-next 217
- [ ] https://github.com/anuoua/unis 216
- [ ] https://github.com/Tinkoff/tramvai 215
- [ ] https://github.com/stephenh/joist-ts 212
- [ ] https://github.com/asyncapi/modelina 210
- [ ] https://github.com/github/codespaces-blank 206
- [ ] https://github.com/SauravKanchan/svelte-chartjs 204
- [ ] https://github.com/ryansonshine/typescript-npm-package-template 204
- [ ] https://github.com/magicdawn/weread-spy 203
- [ ] https://github.com/unplugin/unplugin-swc 203
- [ ] https://github.com/wechaty/puppet 203
- [ ] https://github.com/ThePrimeagen/undefined 200
- [ ] https://github.com/jonataswalker/ol-contextmenu 198
- [ ] https://github.com/payloadcms/next-payload 197
- [ ] https://github.com/sonnyt/just 197
- [ ] https://github.com/theKashey/devolution 195
- [ ] https://github.com/DTStack/dt-sql-parser 195
- [ ] https://github.com/vaheqelyan/react-awesome-popover 194
- [ ] https://github.com/datalanche/node-pg-format 193
- [ ] https://github.com/samhh/fp-ts-std 192
- [ ] https://github.com/nxtend-team/nxtend 191
- [ ] https://github.com/jerrywu001/vue3-toastify 191
- [ ] https://github.com/JasKang/rubic 186
- [ ] https://github.com/sphinx-labs/sphinx 186
- [ ] https://github.com/eggjs/egg-bin 185
- [ ] https://github.com/romgrk/web-toolkit 184
- [ ] https://github.com/jasonraimondi/ts-oauth2-server 184
- [ ] https://github.com/Zapper-fi/studio 183
- [ ] https://github.com/gilbarbara/react-floater 183
- [ ] https://github.com/muxinc/elements 179
- [ ] https://github.com/jaebradley/example-rollup-react-component-npm-package 178
- [ ] https://github.com/ice-lab/icepkg 178
- [ ] https://github.com/bjorn3/browser_wasi_shim 178
- [ ] https://github.com/osmosis-labs/osmosis-frontend 175
- [ ] https://github.com/Gabb-c/pokenode-ts 173
- [ ] https://github.com/Himenon/openapi-typescript-code-generator 171
- [ ] https://github.com/milesj/packemon 169
- [ ] https://github.com/shaoruu/voxelize 167
- [ ] https://github.com/Atyantik/pawjs 165
- [ ] https://github.com/wechat-miniprogram/mobx-miniprogram-bindings 165
- [ ] https://github.com/codermarcos/simple-mask-money 164
- [ ] https://github.com/DevYukine/Kurasuta 160
- [ ] https://github.com/shuding/yoga-wasm-web 160
- [ ] https://github.com/skyllo/peer-lite 159
- [ ] https://github.com/cgxqd/utilscore 158
- [ ] https://github.com/storybookjs/test-runner 158
- [ ] https://github.com/kubb-project/kubb 157
- [ ] https://github.com/agiliumtrade-ai/metaapi-node.js-sdk 156
- [ ] https://github.com/leon-ai/leon-cli 156
- [ ] https://github.com/diegoazh/gmap-vue 156
- [ ] https://github.com/SUI-Components/sui 155
- [ ] https://github.com/Menci/vite-plugin-top-level-await 154
- [ ] https://github.com/demergent-labs/azle 153
- [ ] https://github.com/ShogunPanda/fastimage 152
- [ ] https://github.com/pixelass/react-stickyroll 152
- [ ] https://github.com/storybookjs/telejson 151
- [ ] https://github.com/natalan/samsung-remote 150
- [ ] https://github.com/BySlin/umi-plugin-electron-builder 150
- [ ] https://github.com/chialab/rna 149
- [ ] https://github.com/getjerry/nest-casl 149
- [ ] https://github.com/nextjs-components/nextjs-components 149
- [ ] https://github.com/jspm/generator 148
- [ ] https://github.com/sladg/nextjs-lambda 148
- [ ] https://github.com/tada5hi/typeorm-extension 144
- [ ] https://github.com/pveyes/raw.macro 144
- [ ] https://github.com/yowainwright/shave 143
- [ ] https://github.com/yamadapc/augmented-audio 143
- [ ] https://github.com/dano-inc/react-query-helper 142
- [ ] https://github.com/asyncapi/cli 142
- [ ] https://github.com/adonisjs/ally 141
- [ ] https://github.com/himself65/rich-data 141
- [ ] https://github.com/Janpot/next-rpc 139
- [ ] https://github.com/channel-io/bezier-react 138
- [ ] https://github.com/Jack-Works/async-call-rpc 138
- [ ] https://github.com/ArunMichaelDsouza/joypad.js 137
- [ ] https://github.com/pmndrs/react-ogl 137
- [ ] https://github.com/jinxdash/prettier-plugin-rust 137
- [ ] https://github.com/thirdweb-dev/typescript-sdk 136
- [ ] https://github.com/microcmsio/microcms-js-sdk 134
- [ ] https://github.com/wintercounter/mhy 134
- [ ] https://github.com/infinum/datx 133
- [ ] https://github.com/mantoufan/yzhanWeather 133
- [ ] https://github.com/pubnub/react-chat-components 132
- [ ] https://github.com/Brooooooklyn/pinyin 130
- [ ] https://github.com/alfredosalzillo/rollup-plugin-multi-input 128
- [ ] https://github.com/pradel/create-react-app-swc 128
- [ ] https://github.com/SukkaW/rollup-plugin-swc 125
- [ ] https://github.com/favware/graphql-pokemon 125
- [ ] https://github.com/basilfx/normalize-wheel 123
- [ ] https://github.com/wessberg/Polyfiller 123
- [ ] https://github.com/maugenst/tabletojson 123
- [ ] https://github.com/nrwl/nx-labs 122
- [ ] https://github.com/swc-project/cli 120
- [ ] https://github.com/SaltyAom/kingworld 120
- [ ] https://github.com/zackradisic/tyfsm 117
- [ ] https://github.com/storybookjs/addon-kit 117
- [ ] https://github.com/CodelyTV/typescript-basic-skeleton 117
- [ ] https://github.com/mizdra/happy-css-modules 115
- [ ] https://github.com/n8n-io/n8n-nodes-starter 114
- [ ] https://github.com/javascriptdata/scikit.js 113
- [ ] https://github.com/OMikkel/tailwind-datepicker-react 111
- [ ] https://github.com/texei/texei-sfdx-plugin 110
- [ ] https://github.com/ssssota/svg2png-wasm 109
- [ ] https://github.com/prettydiff/share-file-systems 108
- [ ] https://github.com/adonisjs/validator 108
- [ ] https://github.com/gadget-inc/wds 108
- [ ] https://github.com/shannonhochkins/ha-component-kit 108
- [ ] https://github.com/mantoufan/yzhanHTMLParser 108
- [ ] https://github.com/adonisjs/fold 107
- [ ] https://github.com/nwpointer/three-landscape 105
- [ ] https://github.com/VKCOM/icons 104
- [ ] https://github.com/goldstack/goldstack 103
- [ ] https://github.com/upgradejs/depngn 103
- [ ] https://github.com/jasonkuhrt/alge 101
- [ ] https://github.com/asyncapi/parser-js 101
- [ ] https://github.com/faasjs/faasjs 101
- [ ] https://github.com/jungomi/xxhash-wasm 101
- [ ] https://github.com/SocialGouv/code-du-travail-numerique 101
- [ ] https://github.com/CodelyTV/typescript-primitives-type 100
